import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="coffee">
      <body className={inter.className}>
        <header className="bg-teal-300">
          <h3>this is container header</h3>
        </header>
        {children}
        <footer className="bg-amber-300">
          <h3>this is container footer</h3>
        </footer>
      </body>
    </html>
  );
}
